# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

from scrapy.item import Item, Field

class DaumPeopleNameItem(Item):
    name = Field()
    english_name = Field()
    daum = Field()
    naver = Field()
    joins = Field()
    last_updated = Field(serializer=str)

class DaumPeopleProfileItem(Item):
    name = Field()
    job = Field()
    gender = Field()
    legal_name = Field()
    english_name = Field()
    chinese_name = Field()
    site_official = Field()
    site_twitter = Field()
    site_facebook = Field()
    site_cyworld = Field()
    site_me2day = Field()
    site_youtube = Field()
    site_fancafe = Field()
    birthday = Field()
    birthplace = Field()
    deathday = Field()
    age = Field()
    weight = Field()
    height = Field()
    debut = Field()
    debut_year = Field()
    belong_id = Field()
    belong = Field()
    zodiac_sign_chinese = Field()
    zodiac_sign_star = Field()
    blood_type = Field()
    members = Field()
    member_count = Field()
    belong_group = Field()
    belong_group_keys = Field()
    d_movie_id = Field()
    d_homodic_id = Field()
    d_music_id = Field()
    d_thumbnail_url = Field()
    image_urls = Field()
    images = Field()
    thumbnail_filename = Field()
    last_updated = Field(serializer=str)


class DaumKeywordPvItem(Item):
    name = Field()
    female = Field()
    male = Field()
    age_00 = Field()
    age_10 = Field()
    age_20 = Field()
    age_30 = Field()
    age_40 = Field()
    age_50 = Field()
    label_1 = Field()
    label_2 = Field()
    label_3 = Field()
    label_4 = Field()
    label_5 = Field()
    label_6 = Field()
    label_7 = Field()
    label_8 = Field()
    label_9 = Field()
    month_1 = Field()
    month_2 = Field()
    month_3 = Field()
    month_4 = Field()
    month_5 = Field()
    month_6 = Field()
    month_7 = Field()
    month_8 = Field()
    month_9 = Field()
    last_updated = Field(serializer=str)
